# Generated by Django 5.2.8 on 2025-11-07 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('quantity_at_alert', models.IntegerField()),
                ('threshold_at_alert', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('alert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('email_sent_to', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory_app.sparepart')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-alert_date'],
            },
        ),
    ]
