# Generated by Django 5.2.8 on 2025-11-07 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alertlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('low_stock_count', models.IntegerField(default=0)),
                ('recipients', models.TextField()),
                ('email_sent_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Daily Alert Log',
                'verbose_name_plural': 'Daily Alert Logs',
                'ordering': ['-alert_date'],
                'constraints': [models.UniqueConstraint(fields=('alert_date',), name='unique_daily_alert')],
            },
        ),
    ]
